### ISSUE TITLE
HOW DO I MAKE THE AI WORK

### ISSUE THREAD

**Issue by ilovebeluga** [HydraDragonAntivirus/HydraDragonAntivirus#3]
tell me

**Comment by HydraDragonAntivirus** [comment]
If you mean machine learning AI, you can download malware and benign database then compile it. If you mean Llama3.2 https://huggingface.co/meta-llama/Llama-3.2-1B/tree/main I was using this, and I can release pre-beta version of AV at google drive because AI makes file bigger than 2GB.

**Comment by ilovebeluga** [comment]
ok but how do i compile it?

**Comment by HydraDragonAntivirus** [comment]
> ok but how do i compile it?

If you mean machine learning AI  https://github.com/HydraDragonAntivirus/HydraDragonAntivirus/blob/main/machinelearning/train.py you can use this.
